---
- name: Delete previous server if exists
  hosts: localhost
  vars:
    tripleo_admin_pub_key: "{{ lookup('file', '../tripleo-ci-team') }}"
    tebroker_int_ip: 192.168.103.254
    tebroker_image: CentOS-7-x86_64-GenericCloud-1801-01
    tebroker_flavor: ci.m1.medium
    keypair_name: tripleo-cd-admins
    tebroker_secgroups:
      - default
      - sshnaidm_secgroup
  tasks:

    - name: Fail if no auth is provided
      fail:
        msg: 'Please source credential rc file from the tenant on cloud'
      when: "lookup('env', 'OS_USERNAME') == ''"

    - when: (delete_tebroker is defined and delete_tebroker|bool) or (cleanup_all is defined and cleanup_all|bool)
      block:

      - name: Delete a port with fixed IP
        os_port:
          name: te-broker-port
          network: private
          state: absent

      - name: Delete te-broker if exists
        os_server:
          state: absent
          name: te-broker
          delete_fip: true

    - name: Create a port with fixed IP
      os_port:
        name: te-broker-port
        network: private
        state: present
        fixed_ips:
          - ip_address: "{{ tebroker_int_ip }}"
        security_groups: "{{ tebroker_secgroups }}"

    - name: Create the te-broker server instance
      os_server:
        state: present
        name: te-broker
        auto_floating_ip: yes
        flavor: "{{ tebroker_flavor }}"
        image: "{{ tebroker_image }}"
        key_name: "{{ keypair_name }}"
        nics:
          - port-name: te-broker-port
        timeout: 300
        userdata: |
          #cloud-config
          ssh_authorized_keys:
            - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDDhi/BqsZibuAPiUjJe7b3Dqe5nyI7BckOwfGwJYg436+bFQMoR/7RKmtPe+ISVQ04lwIriIPwKGaSHj5mbEe4LsCLZ5jAUHxvWfgHitqS5ln295zU7vp1z28o7e6LQNplgExyqQlxUPdOU48tmlz93F6szSYkNYvZnhzMn9syrajC74qPuKsmHTeYFLEcxesb7/u+BtxCk8WdjYTb//sk038NEtIsNhrGtAOV3WcDpXnA5mNMpUfeoQ4yiN9LqtreXr7Zeo587LV3T2QL+huAE0J7EuCzHAKk6TIzJqjLidg0SYwZZwfbxgviU66QLkeyzh9oiovwskelvOQCBFq3 sshnaidm@sshnaidm.remote.csb.new
          packages:
            - ansible
            - git
          package_upgrade: true
          write_files:
          - content: |
              export OS_USERNAME='{{ lookup('env', 'OS_USERNAME') }}'
              export OS_TENANT_NAME='{{ lookup('env', 'OS_TENANT_NAME') }}'
              export OS_TENANT_ID='{{ lookup('env', 'OS_TENANT_ID') }}'
              export OS_AUTH_URL='{{ lookup('env', 'OS_AUTH_URL') }}'
              export OS_PASSWORD='{{ lookup('env', 'OS_PASSWORD') }}'
              export NODEPOOL_PROVIDER=rdo-cloud-tripleo
            path: /etc/nodepoolrc
            permissions: '0600'
          runcmd:
            - mkdir -p /etc/ansible/
            - echo 'te-broker ansible_host=localhost' >  /etc/ansible/hosts
            - ansible-pull -d /var/lib/ansible/local -U https://github.com/sshnaidm/ci-config.git -C teb2  --clean playbooks/tebroker_playbook.yml 2>&1 >>/var/log/ansible-pull.log
